version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: restnode_app
    depends_on:
      - mysql
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "3000:3000"
    command: npx nodemon server.js
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:
